/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ilab.spark.apps;

import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.streaming.StreamingQueryException;
import org.apache.spark.sql.streaming.Trigger;

import java.util.concurrent.TimeoutException;

import static com.ilab.spark.utils.SparkSessionUtils.createSparkSessionWithDelta;

public class RandomStreamingApp {
    public static void main(String[] args) {

        SparkSession spark =  createSparkSessionWithDelta("DeltaApp");

        Dataset<Row> streamingDf = spark.readStream().format("rate").load();

        try {
            streamingDf.writeStream().trigger(Trigger.ProcessingTime(10000))
                    .format("console")
                    .outputMode("append")
                    .start()
                    .awaitTermination();

        } catch (StreamingQueryException e) {
            throw new RuntimeException(e);
        } catch (TimeoutException e) {
            throw new RuntimeException(e);
        }


    }
}
